import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import "./globals.css";

// Components
import NavBar from "./components/NavBar";
import SessionProvider from "./components/SessionProvider";
import TestingSession from "./components/TestingSession";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <NavBar />
          <TestingSession />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
