DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS menus CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL DEFAULT 'user'
);

CREATE TABLE menus (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id),
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255)
);

CREATE TABLE menu_items (
  id SERIAL PRIMARY KEY NOT NULL,
  menu_id INTEGER REFERENCES menus(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  price NUMERIC NOT NULL
);